# Generated by Django 4.1.3 on 2022-11-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0002_rename_price_savingsproduct_price_before_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
